# Generated by Django 3.1.1 on 2020-09-13 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='color',
            field=models.CharField(default='#eeeeee', max_length=25),
        ),
    ]
